---
- name: 'downloading {{ maven_download_url }}'
  get_url:
    url: '{{ maven_download_url }}'
    dest: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
    url_username: '{{ maven_download_username }}'
    url_password: '{{ maven_download_password }}'
    timeout: 20
  register: maven_download
  until: maven_download.status_code == 200
  retries: 3
  delay: 10
  tags:
    - maven_install

- name: '[fact] set maven archive present'
  set_fact:
    maven_downloaded: true

- name: 'unarchive maven binaries'
  unarchive:
    src: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
    dest: '{{ maven_home_parent_directory }}'
    copy: no
  when: (
    (maven_installed is not defined or maven_installed == false) and
    (maven_downloaded is defined and maven_downloaded == true))

- name: 'create generic link to {{maven_home_parent_directory}}/maven'
  file:
    src: '{{maven_home_parent_directory}}/apache-maven-{{ maven_version }}'
    dest: '{{maven_home_parent_directory}}/maven'
    state: link

- name: 'link {{maven_home_parent_directory}}/maven/bin/mvn to /usr/bin/mvn'
  file:
    src: '{{maven_home_parent_directory}}/maven/bin/mvn'
    dest: '/usr/bin/mvn'
    state: link
