---

- name: '[fact] insert custom fact file for maven'
  template:
    src: facts.d/maven.fact.j2
    dest: /etc/ansible/facts.d/maven.fact
    owner: 'root'
    group: 'root'
    mode: '0755'
  register:
    register_maven_facts

- name: '[fact]  re-run setup to use custom facts'
  action: setup
  when:
    register_maven_facts.changed
