---

- name: create deployment temporary directory
  ansible.builtin.file:
    path: "{{ maven_deployment_tmp_directory }}"
    state: directory
    mode: 0750

- name: create local temporary directory
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: "{{ maven_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: download maven binary to local folder
  delegate_to: localhost
  become: false
  ansible.builtin.get_url:
    url: "{{ maven_download_url }}"
    dest: "{{ maven_local_tmp_directory }}/{{ maven_file_name }}"
    mode: 0640
  register: _download_artefact
  until: _download_artefact is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: deploy {{ maven_file_name }} to destination system
  ansible.builtin.copy:
    src: "{{ maven_local_tmp_directory }}/{{ maven_file_name }}"
    dest: "{{ maven_deployment_tmp_directory }}"
    mode: 0640

- name: unarchive {{ maven_file_name }}
  ansible.builtin.unarchive:
    src: '{{ maven_deployment_tmp_directory }}/{{ maven_file_name }}'
    dest: '{{ maven_home_parent_directory }}'
    copy: false
    mode: 0755

...
