---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: dwonload
  ansible.builtin.include_tasks: download.yml

- name: install
  ansible.builtin.include_tasks: install.yml

- name: cleanup
  ansible.builtin.include_tasks: cleanup.yml

...
