---

# - name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
#   include_vars: "{{ lookup('first_found', params) }}"
#   vars:
#     params:
#       paths:
#         - "vars"
#       files:
#         # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
#         - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
#         # eg. archlinux-systemd / archlinux-openrc
#         - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yaml"
#         # eg. debian / ubuntu / centos / oraclelinux
#         - "{{ ansible_distribution | lower }}.yaml"
#         # eg. redhat / debian / archlinux
#         - "{{ ansible_os_family | lower }}.yaml"
#         - default.yaml
#       skip: true

- name: redhat
  when:
    - ansible_os_family | lower == 'redhat'
  block:
    - name: Import EPEL GPG key.
      ansible.builtin.rpm_key:
        key: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present

    - name: install EPEL repository
      ansible.builtin.yum_repository.yum_repository:
        name: epel
        state: present
        description: Extra Packages for Enterprise Linux {{ ansible_distribution_major_version }} - $basearch
        baseurl: http://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/$basearch
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch&infra=$infra&content=$contentdir
        failovermethod: priority
        gpgcheck: 1
        enabled: 1

- name: update package cache
  ansible.builtin.package:
    update_cache: true

- name: install dependecies
  ansible.builtin.package:
    name: "{{ maven_dependencies }}"
    state: present
  when:
    - maven_dependencies | default([]) | count > 0

- name: check for installed maven
  become: false
  ansible.builtin.stat:
    path: "{{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}/bin/mvn"
  register: _installed_maven

...
