---

driver:
  name: docker

lint: |
    yamllint .
    ansible-lint

platforms:

  - name: centos7
    image: paulfantom/centos-molecule:7
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

#   - name: centos8
#     image: paulfantom/centos-molecule:8
#     docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
#     capabilities:
#       - SYS_ADMIN
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro
#
#   - name: bionic
#     image: paulfantom/ubuntu-molecule:18.04
#     docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
#     capabilities:
#       - SYS_ADMIN
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro
#
#   - name: xenial
#     image: paulfantom/ubuntu-molecule:16.04
#     docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
#     capabilities:
#       - SYS_ADMIN
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro
#
#   - name: jessie
#     image: paulfantom/debian-molecule:8
#     docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
#     capabilities:
#       - SYS_ADMIN
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro
#
#   - name: stretch
#     image: paulfantom/debian-molecule:9
#     docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
#     capabilities:
#       - SYS_ADMIN
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro
#
  - name: buster
    image: paulfantom/debian-molecule:10
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  ansible_args:
    - --diff
  #   - -vvv
  config_options:
    defaults:
      host_key_checking: False
      deprecation_warnings: True
      interpreter_python: auto
      # callback_whitelist: profile_tasks
      # gather_subset: '!hardware'

  lint:
    name: ansible-lint
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: playbook.yml
    destroy: destroy.yml

scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
